config/routes.rb
Rails.application.routes.draw do
  resources :items
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :countries
  resources :addresses do
    resources :address_creations
  end
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :country, required: false

  after_create :send_email

  def full_address
    [street, post_code, country&.title].reject(&:blank?).join(', ')
  end

  def send_email
    MainMailer.after_order_email(id).deliver_later
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/country.rb
class Country < ApplicationRecord
  acts_as_paranoid
  
  has_many :addresses
  validates :title, :iso2, presence: true

  def self.for_select
    order(:title).map { |country| [country.title, country.id] }
  end
end

app/models/item.rb
class Item < ApplicationRecord
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :service
end

app/models/service.rb
class Service < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :trackable
end

app/controllers/address_creations_controller.rb
class AddressCreationsController < ApplicationController
  include Wicked::Wizard

  steps :select_country, :fill_address_details

  def create
    @address = Address.create
    sessions[:country_id] = @address.id
    redirect_to wizzard_path
  end

  def update
    @address = Address.find(params[:address_id])
    @address.update address_params
    render_wizard @address
  end

  def show
    @address = Address.find(params[:address_id])
    render_wizard
  end

  private

  def address_params
    params.require(:address).permit!
  end
end

app/controllers/addresses_controller.rb
class AddressesController < ApplicationController
  def index
    @addresses = Address.all
  end

  def new
    @address = Address.new
    @address.build_country
  end

  def create
    @address = Address.new
    if @address.save
      redirect_to address_address_creation_path(@address.id, :select_country)
    else
      render 'new'
    end
  end

  private

  def address_params
    params.require(:address).permit :name, :email, :phone, :post_code, :street, :country_id,
      country_attributes: [:title, :iso2]
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/countries_controller.rb
class CountriesController < ApplicationController
  before_action :find_country
  before_action :authenticate_user!

  def index
    @q = Country.ransack(params[:q])
    @countries = @q.result(distinct: true)
  end

  def new
    @country = Country.new
  end

  def show
  end

  def edit
  end

  def update
    if @country.update country_params
      redirect_to countries_path
    else
      render :edit
    end
  end

  def create
    @country = Country.new country_params
    if @country.save
      redirect_to countries_path
    else
      render :new
    end
  end

  def destroy
    @country.destroy
    redirect_to countries_path
  end

  private

  def find_country
    @country = Country.find(params[:id]) if params[:id]
  end

  def country_params
    params.require(:country).permit :title, :iso2
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: %i[ show edit update destroy ]

  # GET /items or /items.json
  def index
    @items = Item.all
  end

  # GET /items/1 or /items/1.json
  def show
  end

  # GET /items/new
  def new
    @item = Item.new
  end

  # GET /items/1/edit
  def edit
  end

  # POST /items or /items.json
  def create
    @item = Item.new(item_params)

    respond_to do |format|
      if @item.save
        format.html { redirect_to @item, notice: "Item was successfully created." }
        format.json { render :show, status: :created, location: @item }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /items/1 or /items/1.json
  def update
    respond_to do |format|
      if @item.update(item_params)
        format.html { redirect_to @item, notice: "Item was successfully updated." }
        format.json { render :show, status: :ok, location: @item }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1 or /items/1.json
  def destroy
    @item.destroy
    respond_to do |format|
      format.html { redirect_to items_url, notice: "Item was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Item.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def item_params
      params.require(:item).permit(:title, :description)
    end
end

app/helpers/address_creations_helper.rb
module AddressCreationsHelper
end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/countries_helper.rb
module CountriesHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/address_creations/fill_address_details.html.haml
= simple_form_for @address, url: wizard_path, method: :put do |f|
  = f.input :name
  = f.input :street
  = f.input :post_code

  = @address.country.title

  = f.submit 'Save', class: 'btn btn-success btn-sm'

app/views/address_creations/select_country.html.haml
= simple_form_for @address, url: wizard_path, method: :put do |f|
  = f.input :country_id, collection: Country.for_select
  = f.submit 'Save', class: 'btn btn-success btn-sm'

app/views/addresses/_form.html.haml
= simple_form_for @address do |f|
  = f.submit 'Save', class: 'btn btn-success btn-sm'

app/views/addresses/index.html.haml
%table.table
  %tr
    %td
      Vardas
    %td
      Telefonas
    %td
      El. paštas
    %td
      Pilnas adresas
    %td
  = link_to 'Add new address', new_address_path, class: 'btn btn-success btn-sm'
  - @addresses.each do |address|
    %tr
      %td
        = address.name
      %td
        = address.phone
      %td
        = address.email
      %td
        = address.full_address
      %td
        = link_to 'Peržiūrėti', address_path(address)
        = link_to 'Redaguoti', edit_address_path(address)
        = link_to 'Delete', address_path(address), method: :delete, data: { confirm: 'Are you sure?', disable_with: 'Loading...' }
      

app/views/addresses/new.html.haml
%h1
  New address

= render 'form'

app/views/countries/_form.html.haml
Labai gera form
= simple_form_for @country do |f|
  = f.input :title
  = f.input :iso2
  = f.submit 'Save'

app/views/countries/edit.html.haml
%h1
  Edit

= render 'form'

app/views/countries/index.html.haml
%h1 Hello world!

= simple_form_for @q, url: countries_path, method: :get do |f|
  = f.input :title_cont, required: false
  = f.submit 'Search'

%table.table
  %tr
    %td
      Pavadinimas
    %td
      ISO kodas
    %td
      Veiksmai
  - @countries.each do |country|
    %tr
      %td
        = country.title
      %td
        = country.iso2
      %td
        = link_to 'Peržiūrėti', country_path(country)
        = link_to 'Redaguoti', edit_country_path(country)
        = link_to 'Delete', country_path(country), method: :delete, data: { confirm: 'Are you sure?', disable_with: 'Loading...' }
      

app/views/countries/new.html.haml
%h1
  New

= render 'form'

app/views/countries/show.html.haml
%h1
  = @country.title
%h2
  = @country.iso2

app/views/items/_form.html.erb
<%= simple_form_for(@item) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :title %>
    <%= f.input :description %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/items/edit.html.erb
<h1>Editing Item</h1>

<%= render 'form', item: @item %>

<%= link_to 'Show', @item %> |
<%= link_to 'Back', items_path %>

app/views/items/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Items</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @items.each do |item| %>
      <tr>
        <td><%= item.title %></td>
        <td><%= item.description %></td>
        <td><%= link_to 'Show', item %></td>
        <td><%= link_to 'Edit', edit_item_path(item) %></td>
        <td><%= link_to 'Destroy', item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Item', new_item_path %>

app/views/items/new.html.erb
<h1>New Item</h1>

<%= render 'form', item: @item %>

<%= link_to 'Back', items_path %>

app/views/items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @item.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @item.description %>
</p>

<%= link_to 'Edit', edit_item_path(@item) %> |
<%= link_to 'Back', items_path %>

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title LearningApp
    %meta{:content => "width=device-width,initial-scale=1", :name => "viewport"}/
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    .container{style: 'margin-top: 50px;' }
      .col-12
        = yield